//! The `trivfs_startup` bootstrap rendezvous.
//!
//! When a translator is exec'd by `settrans`, the parent fs hands it a
//! single mach port (the "bootstrap port") set by
//! `task_set_special_port(TASK_BOOTSTRAP_PORT, ...)` in the launcher.
//! The translator's job is to:
//!
//!   1. Create a control port that represents the running translator
//!      instance (allocated through libports → port class + bucket).
//!   2. Send a `fsys_startup` RPC on the bootstrap port telling the
//!      parent "here is my control-port send right; please give me back
//!      a port to the node I'm translating."
//!   3. Stash the returned `underlying` (a.k.a. realnode) port for use
//!      in later operations like `io_stat`.
//!
//! `fsys_startup`'s wire shape transfers port rights, so we can't use
//! the simple-scalar `mig::routine_call!` macro — we hand-roll the
//! request/reply structs here.

use core::ffi::c_void;
use core::ptr::null_mut;

use libc::{c_int, error_t};
use mach_sys::{
    mach_port_deallocate, mach_port_t, mach_task_self,
    MACH_MSG_TYPE_COPY_SEND, MACH_PORT_NULL,
};
use ports_sys::{
    port_bucket, port_class, ports_create_bucket, ports_create_class,
    ports_create_port, ports_get_send_right, ports_port_deref,
};

use crate::cleanup::{trivfs_clean_cntl, trivfs_clean_protid};
use crate::types::TrivfsControl;

/// Allocate (or reuse) a port bucket. Pass `&mut null_mut()` to get a
/// fresh one allocated for you; pass a pre-allocated bucket pointer to
/// reuse it (we just leave it alone in that case).
///
/// Mirrors libtrivfs's `trivfs_add_port_bucket`. The "add" naming is
/// historical — libtrivfs used to track a list of dynamically-allocated
/// buckets for cleanup. We don't, because shutdown never frees its
/// bucket.
#[no_mangle]
pub unsafe extern "C" fn trivfs_add_port_bucket(
    bucket: *mut *mut port_bucket,
) -> error_t {
    if (*bucket).is_null() {
        let new_bucket = ports_create_bucket();
        if new_bucket.is_null() {
            return ENOMEM;
        }
        *bucket = new_bucket;
    }
    0
}

const ENOMEM: error_t = 12;

/// Allocate (or reuse) a control port class.
#[no_mangle]
pub unsafe extern "C" fn trivfs_add_control_port_class(
    class: *mut *mut port_class,
) -> error_t {
    if (*class).is_null() {
        let new_class = ports_create_class(Some(trivfs_clean_cntl), None);
        if new_class.is_null() {
            return ENOMEM;
        }
        *class = new_class;
    }
    0
}

/// Allocate (or reuse) a protid port class.
#[no_mangle]
pub unsafe extern "C" fn trivfs_add_protid_port_class(
    class: *mut *mut port_class,
) -> error_t {
    if (*class).is_null() {
        let new_class = ports_create_class(Some(trivfs_clean_protid), None);
        if new_class.is_null() {
            return ENOMEM;
        }
        *class = new_class;
    }
    0
}

/// Allocate a trivfs_control with the given underlying node port and
/// register it as a port of `control_class`. Mirrors libtrivfs's
/// `trivfs_create_control`. On success, `*control` is non-NULL and
/// holds a reference (released by the caller via `ports_port_deref`).
unsafe fn create_control(
    underlying:     mach_port_t,
    control_class:  *mut port_class,
    control_bucket: *mut port_bucket,
    protid_class:   *mut port_class,
    protid_bucket:  *mut port_bucket,
    control:        *mut *mut TrivfsControl,
) -> error_t {
    let mut raw: *mut c_void = null_mut();
    let err = ports_create_port(
        control_class,
        control_bucket,
        core::mem::size_of::<TrivfsControl>(),
        &mut raw,
    );
    if err != 0 {
        return err;
    }

    let fsys = raw as *mut TrivfsControl;
    // libports zeroes the allocation, but be explicit about the
    // trivfs-private tail we layer on top.
    (*fsys).protid_class  = protid_class;
    (*fsys).protid_bucket = protid_bucket;
    (*fsys).filesys_id    = 0;
    (*fsys).file_id       = 0;
    (*fsys).underlying    = underlying;
    (*fsys).hook          = null_mut();
    *control = fsys;
    0
}

// Pure-Rust fsys_startup client stub, generated by the mig::routine!
// macro from crates/mig-macros. Wire layout matches what gnumach's
// `mig` tool emits for hurd/fsys.defs's fsys_startup (subsystem 22000,
// routine 0; reply id 22100).
//
// Trade-off vs the libhurduser extern: we own the generated code now,
// so wire-format bugs are debuggable. Once every translator has
// migrated, -lhurduser comes out of the link line entirely.
mig::routine! {
    fn fsys_startup = 22000;
    in {
        bootstrap:        mach_port_t;
        openflags:        int;
        control_port:     port_send_poly;
    }
    out {
        realnode:         port_send;
    }
}

/// Standard translator bootstrap. Mirrors libtrivfs's `trivfs_startup`:
/// create a control port, send `fsys_startup` to the bootstrap port,
/// stash the returned underlying node.
///
/// `proc_mark_important` is skipped — it's a nice-to-have (tells proc
/// "don't kill this task"), not load-bearing for the rendezvous. Adding
/// it back is a few-line follow-up once we have a proc-sys binding.
#[no_mangle]
pub unsafe extern "C" fn trivfs_startup(
    bootstrap:      mach_port_t,
    flags:          c_int,
    control_class:  *mut port_class,
    control_bucket: *mut port_bucket,
    protid_class:   *mut port_class,
    protid_bucket:  *mut port_bucket,
    control:        *mut *mut TrivfsControl,
) -> error_t {
    let mut fsys: *mut TrivfsControl = null_mut();
    let err = create_control(
        MACH_PORT_NULL,
        control_class, control_bucket,
        protid_class,  protid_bucket,
        &mut fsys,
    );
    if err != 0 {
        return err;
    }

    // Hand the parent a send right on our control port and complete
    // the fsys_startup handshake via the macro-generated stub above.
    let right = ports_get_send_right(fsys as *mut c_void);
    let mut underlying: mach_port_t = 0;
    let kr = fsys_startup(
        bootstrap,
        flags,
        right,
        MACH_MSG_TYPE_COPY_SEND as c_int,
        &mut underlying,
    );
    mach_port_deallocate(mach_task_self(), right);

    if kr == 0 {
        (*fsys).underlying = underlying;
    }

    ports_port_deref(fsys as *mut c_void);

    if kr == 0 && !control.is_null() {
        *control = fsys;
    }

    kr
}
